{% set name = "yaqd-new-era" %}
{% set version = "2022.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yaqd-new-era-{{ version }}.tar.gz
  sha256: bed0dd006f0f0628597b1090c189c916372093088c6baa06bb2166b76ec73656

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-new-era-ne1000 = yaqd_new_era._new_era_ne1000:NewEraNe1000.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
  run:
    - python >=3.7
    - flit
    - yaqd-core >=2020.06.3
    - pyserial

test:
  imports:
    - yaqd_new_era
  commands:
    - pip check
    - yaqd-new-era-ne1000 --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for new era pump systems hardware
  dev_url: https://gitlab.com/yaq/yaqd-new-era
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
